name: Mirroring

on: [push, delete]

jobs:
  to_gitlab:
    runs-on: ubuntu-latest
    steps:                                              # <-- must use actions/checkout before mirroring!
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@gitlab.com:xfhye3w5rhtrr/china-domain-allowlist.git
          ssh_private_key:                              # <-- use 'secrets' to pass credential information.
            ${{ secrets.GAYHUB_SECRET }}

  to_bitbucket:                                        # <-- different jobs are executed in parallel.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@bitbucket.org:zxecdcdefgrtvxz4b/china-domain-allowlist.git
          ssh_private_key:
            ${{ secrets.GAYHUB_SECRET }}